apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  imagePullSecrets:
        - name: gcr-json-key
  selector:
    app: frontend

