apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  imagePullSecrets:
    - name: gcr-json-key
  selector:
    app: backend
